AWSTemplateFormatVersion: 2010-09-09
Description: "Template for Backend Stack (CodePipeline, ECS Auto Scaling)"

# -------------------------------------
# Metadata
# -------------------------------------
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Project Configuration"
        Parameters:
          - ProjectName
          - Environment
      - Label:
          default: "CloudFormation Configuration"
        Parameters:
          - CodePipelineTemplateURL
          - ECSAutoScalingTemplateURL
      - Label:
          default: "CodePipeline Configuration"
        Parameters:
          # For GitHub
          - BackendRepositoryName
          - SourceBranchName
          - DjangoDockerfilePath
          - NginxDockerfilePath
          - TaskDefinitionTemplatePath
          - AppSpecTemplatePath
          # For CodeBuild
          - ECRBackendDjangoRepositoryName
          - ECRBackendNginxRepositoryName
          # For CodeDeploy
          - CodeDeployApplicationName
          - CodeDeployDeploymentGroupName
          - CodeDeployDeploymentConfigName
          - ECSClusterName
          - ECSServiceName
          - ALBTargetGroupBlueName
          - ALBTargetGroupGreenName
          - ALBProductionListenerArn
          - ALBTestListenerArn
          # For CodeStar
          - CodeStarConnectionArn
          # For CodePipeline Notification
          - CICDPipelineTopicArn
      - Label:
          default: "ECS Auto Scaling Configuration"
        Parameters:
          - ServiceScaleEvaluationPeriods
          - ServiceCPUScaleOutThreshold
          - ServiceCPUScaleInThreshold
          - TaskMinContainerCount
          - TaskMaxContainerCount

# -------------------------------------
# Parameters
# -------------------------------------
Parameters:
  # -------------------------------------
  # Project
  # -------------------------------------
  ProjectName:
    Description: "Enter the project name (ex: my-project)"
    Type: String
    MinLength: 1
    ConstraintDescription: "ProjectName must be enter"
    Default: my-project
  Environment:
    Description: "Select the environment"
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
    ConstraintDescription: "Environment must be select"

  # -------------------------------------
  # CloudFormation
  # -------------------------------------
  CodePipelineTemplateURL:
    Description: "Enter the CodePipeline template object URL in S3 bucket"
    Type: String
  ECSAutoScalingTemplateURL:
    Description: "Enter the ECS Service Auto Scaling template object URL in S3 bucket"
    Type: String

  # -------------------------------------
  # CodePipeline
  # -------------------------------------
  BackendRepositoryName:
    Description: "Enter the target GitHub backend repository name (ex: pj100-team/factor_flow_master_back)"
    Type: String
  SourceBranchName:
    Description: "Enter the source branch name in GitHub backend repository (ex: develop)"
    Type: String
  DjangoDockerfilePath:
    Description: "Enter the Django Dockerfile path in GitHub backend repository (ex: containers/django/Dockerfile.dev)"
    Type: String
  NginxDockerfilePath:
    Description: "Enter the Nginx Dockerfile path in GitHub backend repository (ex: containers/nginx/Dockerfile.dev)"
    Type: String
  TaskDefinitionTemplatePath:
    Description: "Enter the ECS Task Definition template path in GitHub backend repository (ex: ecs/taskdef.dev.json)"
    Type: String
  AppSpecTemplatePath:
    Description: "Enter the Codedeploy Appspec template path in GitHub backend repository (ex: codedeploy/appspec.yml)"
    Type: String
  ECRBackendDjangoRepositoryName:
    Description: "Enter the ECR backend application repository name (ex: my-project/dev/back/django)"
    Type: String
  ECRBackendNginxRepositoryName:
    Description: "Enter the ECR backend webserver repository name (ex: my-project/dev/back/nginx)"
    Type: String
  CodeDeployApplicationName:
    Description: "Enter the CodeDeploy application name (ex: my-project-dev-back-cdapp)"
    Type: String
  CodeDeployDeploymentGroupName:
    Description: "Enter the CodeDeploy deployment group name (ex: my-project-dev-back-cdg)"
    Type: String
  CodeDeployDeploymentConfigName:
    Description: "Select the CodeDeploy deployment config name"
    Type: String
    AllowedValues:
      - CodeDeployDefault.ECSLinear10PercentEvery1Minutes
      - CodeDeployDefault.ECSLinear10PercentEvery3Minutes
      - CodeDeployDefault.ECSCanary10Percent5Minutes
      - CodeDeployDefault.ECSCanary10Percent15Minutes
      - CodeDeployDefault.ECSAllAtOnce
  ECSClusterName:
    Description: "Enter the ECS cluster name (ex: my-project-dev-cluster)"
    Type: String
  ECSServiceName:
    Description: "Enter the ECS service name (ex: my-project-dev-service)"
    Type: String
  ALBTargetGroupBlueName:
    Description: "Enter the ALB target group blue name (ex: my-project-dev-blue-tg)"
    Type: String
  ALBTargetGroupGreenName:
    Description: "Enter the ALB target group green name (ex: my-project-dev-green-tg)"
    Type: String
  ALBProductionListenerArn:
    Description: "Enter the ALB production listener ARN for blue / green deployment"
    Type: String
  ALBTestListenerArn:
    Description: "Enter the ALB test listener ARN for blue / green deployment"
    Type: String
  CodeStarConnectionArn:
    Description: "Enter the CodeStar connection ARN (ex: arn:aws:codestar-connections:<aws_region>:<aws_account_id>:connection/<connection_id>)"
    Type: String
  CICDPipelineTopicArn:
    Description: "Enter the CI/CD SNS Topic ARN (ex: arn:aws:sns:<aws_region>:<aws_account_id>:ai-cicd-pipeline)"
    Type: String

  # -------------------------------------
  # ECS Service Auto Scaling
  # -------------------------------------
  ServiceScaleEvaluationPeriods:
    Description: "The number of periods over which data is compared to the specified threshold"
    Type: Number
    Default: 1
    MinValue: 1
  ServiceCPUScaleOutThreshold:
    Type: Number
    Description: "Average CPU value to trigger auto scaling out"
    Default: 50
    MinValue: 0
    MaxValue: 100
    ConstraintDescription: "ServiceCPUScaleOutThreshold must be between 0 and 100"
  ServiceCPUScaleInThreshold:
    Type: Number
    Description: "Average CPU value to trigger auto scaling in"
    Default: 30
    MinValue: 0
    MaxValue: 100
    ConstraintDescription: "ServiceCPUScaleInThreshold must be between 0 and 100"
  TaskMinContainerCount:
    Type: Number
    Description: "Minimum number of containers to run for the service"
    Default: 1
    MinValue: 1
    ConstraintDescription: "TaskMinContainerCount must be at least one"
  TaskMaxContainerCount:
    Type: Number
    Description: "Maximum number of containers to run for the service when auto scaling out"
    Default: 2
    MinValue: 1
    ConstraintDescription: "TaskMaxContainerCount must be at least one"

# -------------------------------------
# Resources
# -------------------------------------
Resources:
  CodePipelineStack:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref CodePipelineTemplateURL
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        BackendRepositoryName: !Ref BackendRepositoryName
        SourceBranchName: !Ref SourceBranchName
        DjangoDockerfilePath: !Ref DjangoDockerfilePath
        NginxDockerfilePath: !Ref NginxDockerfilePath
        TaskDefinitionTemplatePath: !Ref TaskDefinitionTemplatePath
        AppSpecTemplatePath: !Ref AppSpecTemplatePath
        ECRBackendDjangoRepositoryName: !Ref ECRBackendDjangoRepositoryName
        ECRBackendNginxRepositoryName: !Ref ECRBackendNginxRepositoryName
        CodeDeployApplicationName: !Ref CodeDeployApplicationName
        CodeDeployDeploymentGroupName: !Ref CodeDeployDeploymentGroupName
        CodeDeployDeploymentConfigName: !Ref CodeDeployDeploymentConfigName
        ECSClusterName: !Ref ECSClusterName
        ECSServiceName: !Ref ECSServiceName
        ALBTargetGroupBlueName: !Ref ALBTargetGroupBlueName
        ALBTargetGroupGreenName: !Ref ALBTargetGroupGreenName
        ALBProductionListenerArn: !Ref ALBProductionListenerArn
        ALBTestListenerArn: !Ref ALBTestListenerArn
        CodeStarConnectionArn: !Ref CodeStarConnectionArn
        CICDPipelineTopicArn: !Ref CICDPipelineTopicArn
  ECSAutoScalingStack:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref ECSAutoScalingTemplateURL
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        TargetECSClusterName: !Ref ECSClusterName
        TargetECSServiceName: !Ref ECSServiceName
        ServiceScaleEvaluationPeriods: !Ref ServiceScaleEvaluationPeriods
        ServiceCPUScaleOutThreshold: !Ref ServiceCPUScaleOutThreshold
        ServiceCPUScaleInThreshold: !Ref ServiceCPUScaleInThreshold
        TaskMinContainerCount: !Ref TaskMinContainerCount
        TaskMaxContainerCount: !Ref TaskMaxContainerCount
